"""Execute real snapshot/done/reset methods on CPU tensors; no simulator imports."""
import ast
from collections.abc import Sequence
from copy import deepcopy
import math
from pathlib import Path
import sys
from types import SimpleNamespace

import pytest
import torch

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT / "src"))
from wheeled_tasks.v40 import core


@pytest.fixture
def env():
    path = ROOT / "src/wheeled_tasks/direct/v40_serial/env.py"
    cls = next(n for n in ast.parse(path.read_text()).body if isinstance(n, ast.ClassDef))
    names = {"_make_evaluation_snapshot", "_get_dones", "_reset_idx", "_sample_commands",
             "capture_evaluation_initial_snapshot", "get_evaluation_snapshot", "_joint_state",
             "_contact_magnitudes", "_base_height", "_named_indices"}
    cls.body = [n for n in cls.body if isinstance(n, ast.FunctionDef) and n.name in names]
    cls.bases = [ast.Name(id="ResetBase", ctx=ast.Load())]

    class ResetBase:
        def _reset_idx(self, env_ids):
            self.episode_length_buf[env_ids] = 0

    namespace = dict(torch=torch, math=math, deepcopy=deepcopy, Sequence=Sequence,
                     ResetBase=ResetBase, WHEEL_BODY_NAMES=["L_link3", "R_link3"])
    exec(compile(ast.fix_missing_locations(ast.Module(body=[cls], type_ignores=[])), str(path), "exec"), namespace)
    env = namespace["V40Env"]()
    c = core.load_contract(ROOT / "contracts/own_v40_v2.json")
    q = torch.tensor(c["joints"]["nominal_positions"]).repeat(2, 1)
    pose = torch.tensor([[0., 0., .32, 0., 0., 0., 1.]]).repeat(2, 1)
    tensors = dict(root_link_pose_w=pose, root_link_pos_w=pose[:, :3], root_link_quat_w=pose[:, 3:],
                   root_com_vel_w=torch.zeros(2, 6), root_com_lin_vel_b=torch.zeros(2, 3),
                   root_com_ang_vel_b=torch.zeros(2, 3), joint_pos=q.clone(), joint_vel=torch.zeros_like(q),
                   projected_gravity_b=torch.tensor([[0., 0., -1.]]).repeat(2, 1),
                   applied_torque=torch.zeros_like(q), body_link_pos_w=torch.zeros(2, 7, 3),
                   default_joint_pos=q.clone(), default_root_pose=pose.clone(), default_root_vel=torch.zeros(2, 6))
    data = SimpleNamespace(**{key: SimpleNamespace(torch=value) for key, value in tensors.items()})
    env.__dict__.update(
        contract=c, robot=SimpleNamespace(data=data, body_names=["base_link", "L_link1", "L_link2",
                                                               "L_link3", "R_link1", "R_link2", "R_link3"]),
        num_envs=2, device="cpu", cfg=SimpleNamespace(stage="locomotion"),
        scene=SimpleNamespace(env_origins=torch.zeros(2, 3)),
        contact_sensor=SimpleNamespace(data=SimpleNamespace(
            net_forces_w_history=SimpleNamespace(torch=torch.zeros(2, 2, 7, 3)))),
        _joint_ids=torch.arange(6), _leg_ids=torch.tensor([0, 1, 3, 4]), _knee_ids=torch.tensor([1, 4]),
        _nominal=q[0].clone(), _knee_limits=torch.tensor(list(c["joints"]["knee_hard_limits"].values())),
        _wheel_body_ids=torch.tensor([3, 6]), _non_wheel_body_ids=torch.tensor([0, 1, 2, 4, 5]),
        _finite_state=torch.ones(2, dtype=torch.bool), _invalid_actions=torch.zeros(2, dtype=torch.bool),
        _sustained_failure=core.SustainedFailure(2, "cpu"), torques=torch.zeros(2, 6),
        actions=torch.zeros(2, 6), previous_actions=torch.zeros(2, 6),
        leg_targets=q[:, [0, 1, 3, 4]].clone(), wheel_targets=torch.zeros(2, 2),
        _episode_sums={}, extras={}, common_step_counter=1, _sim_step_counter=2,
        episode_length_buf=torch.ones(2, dtype=torch.long), max_episode_length=2000,
        step_dt=.01, physics_dt=.005, commands=torch.tensor([[0., 0., .32]]).repeat(2, 1),
        _evaluation_command_override=(0., 0., .32), _evaluation_command_pending=False, _evaluation_snapshot=None,
        _command_period_ticks=300, _command_ticks_left=torch.zeros(2, dtype=torch.long),
        _commands_due=torch.zeros(2, dtype=torch.bool), history=core.NoisyHistoryStack(2, "cpu"),
    )
    env._base_visual_clearance = lambda: env._base_height() - .17

    # The adapter writes tensors only; no contacts/dynamics are generated by reset.
    def write_pose(root_pose, env_ids):
        data.root_link_pose_w.torch[env_ids] = root_pose
        data.projected_gravity_b.torch[env_ids] = torch.tensor([0., 0., -1.])

    def write_velocity(root_velocity, env_ids):
        data.root_com_vel_w.torch[env_ids] = root_velocity

    def write_joints(position, velocity, env_ids):
        data.joint_pos.torch[env_ids] = position
        data.joint_vel.torch[env_ids] = velocity

    env.robot.write_root_pose_to_sim_index = write_pose
    env.robot.write_root_velocity_to_sim_index = write_velocity
    env.robot.write_joint_state_to_sim_index = write_joints
    env.robot.set_joint_effort_target_index = lambda **kwargs: None
    return env


def test_real_diagnostics_do_not_borrow_suppressed_v2_termination_flags(env):
    data = env.robot.data
    data.root_link_pos_w.torch[0, 2] = .10
    data.projected_gravity_b.torch[0] = torch.tensor([.8, 0., -.6])
    data.joint_pos.torch[0, 1] = 1.
    env.contact_sensor.data.net_forces_w_history.torch[0, 0, 1, 2] = 16.
    terminated, _ = env._get_dones()
    assert not terminated.any()
    snapshot = env.get_evaluation_snapshot()
    assert snapshot["diagnostic_flags_version"] == 1
    for key in ("non_wheel_contact", "knee_limit", "instantaneous_tilt", "low_height", "base_visual_bounds_ground"):
        assert snapshot["diagnostic_flags"][key].tolist() == [True, False]
    assert not any(flag.any() for flag in snapshot["termination_flags"].values())
    assert not snapshot["diagnostic_flags"]["sustained_failure"].any()
    assert not snapshot["diagnostic_flags"]["nonfinite"].any()
    assert snapshot["non_wheel_net_force_max_n"].tolist() == [16., 0.]
    assert env.extras["log"]["Diagnostic/non_wheel_contact"] == .5
    assert env.extras["log"]["Termination/non_wheel_contact"] == 0


def test_sustained_boundary_partial_reset_and_terminal_snapshot_ownership(env):
    env.robot.data.projected_gravity_b.torch[:, 2] = 0.
    for tick in range(1, 101):
        env.common_step_counter = tick
        assert not env._get_dones()[0].any()
    snapshot = env.get_evaluation_snapshot()
    assert snapshot["diagnostic_flags"]["failure_gravity"].all()
    assert snapshot["diagnostic_flags"]["instantaneous_tilt"].all()
    assert not snapshot["diagnostic_flags"]["sustained_failure"].any()
    assert snapshot["sustained_failure_ticks"].tolist() == [100, 100]
    env._get_dones()
    assert env._sustained_failure.count.tolist() == [100, 100]
    env.common_step_counter = 101
    assert env._get_dones()[0].all()
    terminal = env.get_evaluation_snapshot()
    assert terminal["termination_flags"]["tilt"].all()
    assert terminal["diagnostic_flags"]["sustained_failure"].all()
    env._reset_idx([0])
    assert env._sustained_failure.count.tolist() == [0, 101]
    env._get_dones()  # A duplicate after reset must not replace the terminal tick.
    assert env.get_evaluation_snapshot()["diagnostic_flags"]["sustained_failure"].all()
    terminal["diagnostic_flags"]["sustained_failure"].zero_()
    assert env.get_evaluation_snapshot()["diagnostic_flags"]["sustained_failure"].all()
    env.common_step_counter = 102
    assert env._get_dones()[0].tolist() == [False, True]
    assert env.get_evaluation_snapshot()["diagnostic_flags"]["sustained_failure"].tolist() == [False, True]


def test_post_reset_initial_diagnostics_are_fresh_without_overwriting_terminal(env):
    env._invalid_actions[:] = True
    assert env._get_dones()[0].all()
    env._reset_idx([0, 1])
    env._finite_state[:] = False  # Deliberately stale; not a source of snapshot diagnostics.
    env.contact_sensor.data.net_forces_w_history.torch[0, 0, 1, 2] = 7.
    initial = env.capture_evaluation_initial_snapshot()
    assert initial["sample_kind"] == "initial" and initial["state_phase"] == "post_reset"
    assert initial["termination_flags"] == {} and not initial["terminated"].any()
    assert not initial["diagnostic_flags"]["nonfinite"].any()
    assert initial["diagnostic_flags"]["non_wheel_contact"].tolist() == [True, False]
    assert initial["sustained_failure_ticks"].tolist() == [0, 0]
    assert env._sustained_failure.ticks.tolist() == [-1, -1]
    assert env.get_evaluation_snapshot()["diagnostic_flags"]["nonfinite"].all()
    initial["diagnostic_flags"]["non_wheel_contact"].zero_()
    assert env.capture_evaluation_initial_snapshot()["diagnostic_flags"]["non_wheel_contact"][0]
    env.episode_length_buf[0] = 1
    with pytest.raises(RuntimeError, match="followed by reset"):
        env.capture_evaluation_initial_snapshot()


@pytest.mark.parametrize("field", ["gravity", "pose", "velocity", "joint", "torque", "contact", "action"])
def test_nonfinite_is_captured_from_current_state_and_independent_per_env(env, field):
    data = env.robot.data
    tensors = {"gravity": data.projected_gravity_b.torch, "pose": data.root_link_pose_w.torch,
               "velocity": data.root_com_vel_w.torch, "joint": data.joint_pos.torch,
               "torque": env.torques, "contact": env.contact_sensor.data.net_forces_w_history.torch}
    if field == "action":
        env._invalid_actions[0] = True
    else:
        tensors[field][0].flatten()[0] = float("nan")
    assert env._get_dones()[0].tolist() == [True, False]
    snapshot = env.get_evaluation_snapshot()
    assert snapshot["diagnostic_flags"]["nonfinite"].tolist() == [True, False]
    assert snapshot["termination_flags"]["nonfinite"].tolist() == [True, False]


def test_v1_instantaneous_termination_keeps_original_meaning(env):
    env.contract = core.load_contract(ROOT / "contracts/own_v40_v1.json")
    env.robot.data.projected_gravity_b.torch[0] = torch.tensor([.8, 0., -.6])
    assert env._get_dones()[0].tolist() == [True, False]
    snapshot = env.get_evaluation_snapshot()
    assert snapshot["termination_flags"]["tilt"].tolist() == [True, False]
    assert snapshot["diagnostic_flags"]["instantaneous_tilt"].tolist() == [True, False]
    assert not snapshot["diagnostic_flags"]["sustained_failure"].any()
